apiVersion: v1
kind: Pod
metadata:
  namespace: "its-jenkins-prod" # Kubernetes pod namespace, central IT-s Jenkins
spec:
  imagePullSecrets:
    - name: pnp-secret
  containers:
    - name: helm
      image: dpdhl.css-thcr-pi.azure.deutschepost.de/cdlib/helm:latest
      tty: true
      command:
        - cat
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 400m
          memory: 512Mi
      imagePullPolicy: Always
      workingDir: "/var/lib/jenkins"
