= CDlib-CLI
:toc:
:keywords: latest

This cli aids automating various P&P processes.

== Preparation

In theory you can run our cli locally or inside every CI/CD tool with your preferred container runtime, but currently we only support `Jenkins`, `GitHub Actions` and `Azure Pipelines` for certain steps, e.g. deriving names from tool specific environment variables with `names create`.

=== Jenkins

Set the following environment variables on pipeline level:

[source,groovy]
----
include::../../cli/Jenkinsfile[tags=cli,indent=0]
----

> make sure that you have a B2B proxy clearance or use another proxy if you need to

Then you can add our cli to your xref:Tutorials/KubernetesAsJenkinsAgent.adoc[agent.yaml] like this:

[source,yaml]
----
include::../../cli/agent.yml[tags=cli,indent=0]
----

=== Azure DevOps Pipelines

We only support xref:Tutorials/ManagedDevOpsPools.adoc[Managed DevOps Pools agents].

You can call cdlib-cli like this:

[source,yaml]
----
include::../../cdaas/ado/container-job-templates/cdlib-names-create-stage.yaml[tags=cli,indent=0]
----

== GitHub Actions

You can call cdlib-cli as shown in this reusable workflow: https://git.dhl.com/CDLib/cdaas-workflows/blob/main/.github/workflows/changeclose.yaml

== Usage

=== `-h`: Display Help

Use `cdlib -h` to get help.

> pro tip: works for all the subcommands as well :)

=== `names create`: Create Names

The names created with this command can be used for version names, release names, tags, etc.

Please make sure that you execute this command in a directory where a git checkout is present, as we use this to determine the last commit to fetch meta information about it.

The optional parameter `-f | --outfile` specifies the name of a file to capture the results.
The default is to write to STDOUT.

The optional parameter `--from-release-name` specifies a release name previously generated by CDLib CLI for split pipelines.
The default is to generate the release name and dependent values from the environment.

The optional parameter `-g | --gitpath` specifies the path to the repository with the commit triggering the build or the last commit if the pipeline was triggered manually (in the effective branch).

==== Jenkins

[source,groovy]
----
include::../../cli/Jenkinsfile[tags=cli-nc,indent=0]
----

> in case you checkout your pipeline to a subdirectory (e.g.`checkoutToSubdirectory('src/payment')`), please make sure to execute the command inside this directory (e.g. `dir('src/payment') { ... }`)

==== Azure DevOps Pipelines

Azure Pipelines doesn't have job/stage-wide environment variables, so we have to create the variables first in a separate stage `CDLIB_CREATE_STAGE` and then for every stage that requires the variables created, you have to create a dependency and remap the values.

Below you can see how to create the names depending on your agent.

[source,yaml]
----
include::../../cdaas/ado/container-job-templates/cdlib-names-create-stage.yaml[indent=0]
----

After that you can remap the names like this:

[source,yaml]
----
include::../../cdaas/ado/container-job-templates/cdlib-names-remap-stage.yaml[indent=0]
----

==== GitHub Actions
Not used for GitHub Actions, instead provide the envs as used within our reusable workflows: https://git.dhl.com/CDLib/cdaas-workflows/blob/main/.github/workflows/changeclose.yaml

=== `change create`: Create Changes, Perform Webapproval and Perform OSLC

This step creates the change ticket and is part of the xref:Tutorials/IntegratedChangeManagement.adoc[Integrated Change Management] - since it's usage is described there, we won't do it here.

It will close all pending changes unless you provide the flag `--resume true` then it will resume the latest change for this pipeline.
This can be used for failed deployments of critical systems to avoid manual re-authorization.

Use the flag `--approval-interval-in-minutes` to set the interval in minutes that the change approval is queried via Jira API.
Use the flag `--skip-approval-wait` to skip the approval wait time entirely (useful for integration test scenarios, where no manual approval is required (preauthorized changes).

The optional flag `--test` has multiple effects:

* runs the change request against the test project (SMCHMONB) of the Change Management for implementation testing
* appends `_TEST` to folders when interacting with artifactory
* doesn't actually wait on approvals (although it says so), for quicker testing
* creates webapproval record on the Sharepoint https://itm.prg-dc.dhl.com/sites/it-sec/_layouts/15/start.aspx#/Lists/Pipeline%20Approvals/AllItems.aspx[test list]
* creates tqs record on the TQS Sharepoint Online https://dpdhl.sharepoint.com/teams/TQSDatenaustausch/Lists/Release_Scans_TEST/AllItems.aspx[test list]
* creates oslc record on the OSLC Sharepoint Online https://dpdhl.sharepoint.com/teams/OSLCReporting/Lists/OSLC_Ergebnisse_TEST/AllItems.aspx[test list]

> HINT: in case you have no Jenkins or Azure Pipelines, as you execute the cli locally, you need to set the ENV `CDLIB_JOB_URL` - ideally linking to the execution environment of the command, like a Teamcity run log

==== `--webapproval` flag

> on by default, disable it via --no-webapproval, but only in case your application doesn't require a webapproval

This flag allows you to perform the xref:Tutorials/IntegratedWebApproval.adoc[Integrated Webapproval] as part of `change create`.

In short, it will verify the reports, ensure that the required documents are up-to-date and after the change is approved, it will create a record in Sharepoint of security.

If you have questions about report verification see `report check`.

There are a few prerequisites for this step:

* firewall clearance to https://lcm.deutschepost.de
* firewall clearance to https://itm.prg-dc.dhl.com
* the reports have been uploaded via `report upload`
* there is an immutable repository where files can be stored after the webapproval

With the flag `--skip-cca` you can exempt the results of the Container Composition Analysis provided via `cdlib report fetch css` from the build breaker, since it is optional for webapproval.

The option `--folder-name` can be specified multiple times.

More details, like how to find the `--application-id` and the sharepoint credentials can be found in our xref:Tutorials/IntegratedWebApproval.adoc[Integrated Web Approval Tutorial]

==== `--oslc` flag

> on by default, disable it via --no-oslc, but only in case your application doesn't require a license analysis

This flag allows you to perform the xref:Tutorials/IntegratedOpenSourceLicenseComplianceVerification.adoc[Integrated Open Source License Compliance Verification] as part of `change create`.

In short, it will verify the report and after the change is approved, it will create a record in Sharepoint of OSLC.

Furthermore, you need to add a flag that tells CDlib whether your application is distributed outside our control (`--distribution`, e.g. a mobile app) or remains on our hardware (`--no-distribution`) - as different scan profiles and rules apply to each.

If you have questions about report verification see `report check`.

There are a few prerequisites for this step:

* firewall clearance to https://graph.microsoft.com and https://login.microsoftonline.com

> when using TCB proxy, make sure that you set JAVA_TOOL_OPTIONS="-Dhttps.proxyHost=host -Dhttps.proxyPort=port"

The option `--folder-name` can be specified multiple times.

More details can be found in our xref:Tutorials/IntegratedOpenSourceLicenseComplianceVerification.adoc[Integrated Open Source License Compliance Verification Tutorial]

===== `--output-urls-file` flag

This is an optional flag.
The option `--output-urls-file` lets you specify a file where generated URLs are exported as JSON.
This is handy if you need to parse any of the generated URLs.
During the change process the following URLs will be generated if the appropriate flag is set:

* Jira change url
* Artifactory immutable repository url
* Webapproval Sharepoint url
* OSLC Sharepoint urls
* TQS Sharepoint urls

=== `change close`: Close Changes and Report Metrics

This step closes the change ticket in case the deployment was successful and is part of the xref:Tutorials/IntegratedChangeManagement.adoc[Integrated Change Management] - since it's usage is described there, we won't do it here.

The required parameter `--jira-token` specifies the token for accessing our Change Management tool Jira.
A guide to generate a personal access token can be found xref:Tutorials/ToolAuthentication.adoc[here].

The required parameter `--commercial-reference` specifies the commercial reference (i.e. Leistungsschein) of the project to be set for the change ticket.

The parameter `--status` specifies the status ('SUCCESS', 'FAILURE', 'ABORTED', 'UNSTABLE') to be set for the metrics pushed to the Devops Dashboard.

The optional flag `--test` runs the change request against the test instance of the Change Management API for implementation testing.

The optional `--deployment-type` can be either `APP` (default) or `INFRA` and influences which data is reported to the dashboard.

The `--immutable-repo-name` and `--artifactory-identity-token` parameters are required to create the correct reporting data for an `APP` deployment.
They are currently not enforced but will be in a future release.

The `--artifactory-azure-instance` parameter switches the internally used artifactory instance to the one in Azure.
False by default. Mutually exclusive with `--artifactory-its-instance`.

The `--artifactory-its-instance` parameter switches the internally used artifactory instance to the IT-S one.
False by default. Mutually exclusive with `--artifactory-azure-instance`.

The `--artifactory-identity-token` parameter sets the Artifactory Identity Token according to CDlib tutorial.

This step requires firewall clearance to:

* CDlib Dashboard (https://git.dhl.com/CDLib/CDlib/issues/new?assignees=ab6jg8%2C+omh9ote011&labels=%3Afire%3A+%3Akey%3A+Firewall&template=firewall-request.md&title=firewall+request+XYZ[open a ticket here to request clearance])
** https://cdlib-dashboard-npi.documents.azure.com
** https://cdlib-dashboard-npi-westeurope.documents.azure.com
** https://cdlib-dashboard.documents.azure.com
** https://cdlib-dashboard-westeurope.documents.azure.com
* https://lcm.deutschepost.de (ask LCM team via helpdeskbrief@deutschepost.de to clear it)

=== `report upload`: Check your reports and upload them for release candidates

This command checks your reports for issues and uploads them to artifactory.

> This is the recommended way to upload reports as it creates intermediate files that are required by `change create --webapproval`

> Requires firewall clearance to https://lcm.deutschepost.de

Since it combines `report check` and `archive upload`, the parameters and requirements are largely the same.

> You need to https://devsecops.dhl.com/services/build/artifactory/[create a generic repo inside LCM Artifactory] and also an xref:Tutorials/ToolAuthentication.adoc[Artifactory Identity Token] before you can upload files.

The `--type` parameter is required to specify whether the reports belong to a BUILD (e.g. SAST,SCA,CCA) or RELEASE (e.g. DAST) pipeline.

The `-f, --files` parameter can be specified multiple times and supports ANT patterns for relative paths.
Note that this will upload all files (not just security reports) for convenience.

The `--artifactory-azure-instance` parameter switches the internally used artifactory instance to the one in Azure.
False by default. Mutually exclusive with `--artifactory-its-instance`.

The `--artifactory-its-instance` parameter switches the internally used artifactory instance to the IT-S one.
False by default. Mutually exclusive with `--artifactory-azure-instance`.

The `--artifactory-identity-token` parameter sets the Artifactory Identity Token according to CDlib tutorial.

For more information see `report check` below.

> More details concerning the webapproval can be found xref:Tutorials/IntegratedWebApproval.adoc[in our dedicated tutorial].

=== `report check`: Check your reports for issues for feature branches

This command will check your reports for results, e.g. vulnerabilities.
It currently supports:

- OWASP Dependency check .json
- OWASP ZAP .json
- Fortify .fpr
- CCA reports from `report fetch css`
- OSLC FNCI reports from `report fetch fnci`
- OSLC Maven Plugin report .json
- OSLC Gradle Plugin report .json
- OSLC NPM Plugin report .json
- Sonarqube TQS .zip

> This command is the recommended build breaker if you do not want to release this build later, e.g. if you are not on master.
Otherwise, you must use `report upload` since it creates intermediate files for the xref:Tutorials/IntegratedWebApproval.adoc[Integrated Webapproval] and xref:Tutorials/IntegratedOpenSourceLicenseComplianceVerification.adoc[Integrated Open Source License Compliance Verification]

The `--files`/`-f` parameter can be specified multiple times and supports https://docs.micronaut.io/latest/api/io/micronaut/core/util/AntPathMatcher.html[Ant style patterns].

The `--severity`/`-s` parameter can be used to set minimum failure severity out of `UNKNOWN`/`LOW`/`MEDIUM`/`HIGH`/`CRITICAL` for all security reports.
The command defaults to `HIGH`.

> The other commands will always use `HIGH` with no option to override.

It expects that the following environment variables are present, ideally created with the command `cdlib names create` as explained above (alternatively you can provide them directly, e. g. via export):

- CDLIB_APP_NAME
- CDLIB_PM_GIT_ID
- CDLIB_PM_GIT_NAME
- CDLIB_PM_GIT_LINK
- CDLIB_PM_GIT_MAIL
- CDLIB_PM_GIT_ORIGIN
- CDLIB_PM_GIT_MESSAGE
- CDLIB_CICD_PLATFORM
- CDLIB_JOB_URL

There are optional parameter that can be used if your solution sets a different prefix for some report files.
The prefixes are listed below with their argument names and default values.

|===
|Prefix | Default Value

| --report-prefix-zap | `zap`
| --report-prefix-odc | `dependency-check`
| --report-prefix-fortify | `fortify`
| --report-prefix-tqs| `TQS_Reports`
| --report-prefix-oslc | `oslc-fnci-report`
| --report-prefix-oslc-maven-plugin | `oslc-maven-plugin-report`
| --report-prefix-oslc-gradle-plugin | `oslc-gradle-plugin-report`
| --report-prefix-oslc-npm-plugin | `oslc-npm-plugin-report`
|===

The `--oslc-accepted-list` parameter can be specified to overwrite license information of specific packages or mark it as accepted in the internal OSLC Compliance check.
It accepts the path to a JSON-File defining the overwrites.
For further information read xref:Tutorials/OpenSourceLicenseComplianceScan.adoc[OSLC tutorial].

> If you run into `Java heap space Exception` try increasing the memory limit of the cdlib-cli container.

=== `report fetch`

This command allows you to fetch reports from remote scanners:
- for CCA from Harbors Trivy `cdlib fetch report ccs` - learn more about in our xref:Tutorials/ContainerCompositionAnalysis.adoc[CCA tutorial]
- for OSLC from FNCI `cdlib fetch report fnci` - learn more about in our xref:Tutorials/OpenSourceLicenseComplianceScan.adoc[OSLC tutorial]

> in case it usually takes longer for your report to generate, you can specify `--timeout-in-minutes` to adapt the wait time
