package de.deutschepost.sdm.cdlib.names

enum class Names {
    CDLIB_APP_NAME,
    CDLIB_APP_VERSION,
    CDLIB_BUILD_NUMBER,
    CDLIB_CHART_VERSION,
    CDLIB_CHART_VERSION_OCI,
    CDLIB_CONTAINER_TAG,
    CDLIB_EFFECTIVE_BRANCH_NAME,
    CDLIB_JOB_URL,
    CDLIB_PM_GIT_ID,
    CDLIB_PM_GIT_LINK,
    CDLIB_PM_GIT_MAIL,
    CDLIB_PM_GIT_MESSAGE,
    CDLIB_PM_GIT_NAME,
    CDLIB_PM_GIT_ORIGIN,
    CDLIB_RELEASE_NAME,
    CDLIB_RELEASE_NAME_FORTIFY,
    CDLIB_RELEASE_NAME_HELM,
    CDLIB_RELEASE_VERSION,
    CDLIB_REVISION,
    CDLIB_SANITIZED_BRANCH_NAME,
    CDLIB_SEMANTIC_VERSION,
    CDLIB_TERRAFORM_PREFIX,
    CDLIB_RELEASE_NAME_UNIQUE,
    CDLIB_CICD_PLATFORM,
    CDLIB_PIPELINE_URL
}
